config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  get 'user/:id' => 'users#show', as: :user
  get 'users' => 'users#index', as: :user_index
  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  
  resources :conversations do
    member do
      post :reply
    end
  end

  resources :messages, only: [:new, :create]
  devise_for :users 
  resources :articles do 
    collection do 
      get 'search'
    end
  end
  root 'welcome#home'

  get 'welcome/about'
  get 'welcome/index'

  
  resources :users do
    member do
      get :follow
      get :unfollow
    end
    
  end

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
 devise :database_authenticatable, :trackable, :timeoutable, :lockable
         
end

app/models/article.rb
class Article < ActiveRecord::Base

validates :title, presence: true, length: { minimum: 3, maximum: 50}
validates :description, presence: true, length: {minimim: 10, maximum: 2000 }
belongs_to :user
acts_as_followable
searchkick

end

app/models/follow.rb
class Follow < ActiveRecord::Base

  extend ActsAsFollower::FollowerLib
  extend ActsAsFollower::FollowScopes

  # NOTE: Follows belong to the "followable" interface, and also to followers
  belongs_to :followable, :polymorphic => true
  belongs_to :follower,   :polymorphic => true

  def block!
    self.update_attribute(:blocked, true)
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_attached_file :image,
	styles: { medium: "200x300>", thumb: "100x100>" },
	default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  has_many :articles
  acts_as_followable
  acts_as_follower
  acts_as_messageable
  
   def mailboxer_name
    self.name
  end

  def mailboxer_email(object)
    self.email
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	 
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  helper_method :mailbox

  private

  def mailbox
    @mailbox ||= current_user.mailbox
  end

  def conversation
    @conversation ||= mailbox.conversations.find(params[:id])
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :first_name,:last_name, :address,:gender, :DOB, :email, :password, :password_confirmation, :image, :thumb, :medium, :search])
  end


end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :add_current_user, axcept: [:index]
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  

  def search
    if params[:search].present?
      @articles = Article.search(params[:search])
    else
      @articles = Article.all
    end
  end

  def index
    @articles = Article.order('created_at DESC').paginate(page: params[:page], per_page: 5)
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = current_user.articles.build
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article=Article.new(article_params)
    @article.user=current_user
    if @article.save
    flash[:success] = "Article was successfully created"
    redirect_to article_path(@article)
    else
    render 'new'
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def add_current_user
      unless user_signed_in?
        redirect_to user_session_path
        flash[:warning] = "please sign in"
      end
    end
    
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :description)
    end
    
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
	 before_action :authenticate_user!

  def new
  end
  def create
    recipients = User.where(id: conversation_params[:recipients])
    conversation = current_user.send_message(recipients, conversation_params[:body], conversation_params[:subject]).conversation
    flash[:success] = "Your message was sent"
    redirect_to conversation_path(conversation)
  end

  def show
  	@receipts = conversation.receipts_for(current_user)
  	conversation.mark_as_read(current_user)
  end

  def reply
    current_user.reply_to_conversation(conversation, message_params[:body])
    flash[:notice] = "Your reply sent!"
    redirect_to conversation_path(conversation)
  end
  
  private

  def conversation_params
    params.require(:conversation).permit(:subject, :body,recipients:[])
  end
  
  def message_params
    params.require(:message).permit(:body, :subject)
  end

end

app/controllers/mailbox_controller.rb
class MailboxController < ApplicationController
	before_action :authenticate_user!

  def inbox
    @inbox = mailbox.inbox
    @active = :inbox
  end

  def sent
    @sent = mailbox.sentbox
    @active = :sent
  end

  def trash
    @trash = mailbox.trash
    @active = :trash
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index 
		@users= User.order('created_at DESC').paginate(page: params[:page], per_page: 5)
		
	end
	
  def show
  	@user = User.find(params[:id])
  end
  def follow
  	@user = User.find(params[:id])
  	if current_user
    	current_user.follow(@user)

    	flash[:notice] = "You are now following #{@user.first_name}"
    	redirect_to :back
    end
  end
  def unfollow
  	@user = User.find(params[:id])
  	if current_user
	  	current_user.stop_following(@user)
	  	flash[:notice] = "you ae no longer following #{@user.first_name}"
	  	redirect_to :back
	  end
  end
  def following
    @users = user.all_following
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
  end

  def about
  end

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def active_page(active_page)
    @active == active_page ? "active" : ""
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper

end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/mailbox_helper.rb
module MailboxHelper
	def unread_messages_count
   	mailbox.inbox(:unread => true).count(:id, :distinct => true)
  end
end

app/helpers/users_helper.rb
module UsersHelper
	
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_article.html.erb
<% obj.each do |article| %>
  <div class="row">
    <div class=" col-xs-8 col-xs-offset-2">
      <div class="well well-lg">
        <div class="article-title">
          <%= link_to article.title, article_path(article) %>
        </div>
  
          <div class="article-body">
            <%= truncate(article.description, length: 100) %>
            <div class= "article-details">
              <small>created by: <%= article.user.first_name if article.user%>
                <%= time_ago_in_words(article.created_at)%> ago,
                last update: <%= time_ago_in_words(article.updated_at)%> ago
              </small>
            </div>
          </div>
            <div class= "article-actions">
              <% if current_user && current_user.admin? %>
              <%= link_to " edit this article", edit_article_path(article), class: "btn btn-xs btn-primary" %>
              <%= link_to "Delete this article", article_path(article), method: :delete, data: { confirm: "Are you sure you want to delete the article?"}, class: "btn btn-xs btn-danger" %>  
              <%end %>   
            </div>
          </div>
      </div>
    </div>
 <% end %>

app/views/articles/_form.html.erb
<%= render 'shared/error', obj: @article %>
<div class= 'row'>
  <div class= 'col-xs-12'>
    <%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class= "form-group">
        <div class= "control-lable col-sm-2">
          <%= f.label :title %>
        </div>
        <div class= "col-sm-8">
        <%= f.text_field :title, class: "form-control", placeholder: "Title of aticle", autofocus: true %>
        </div>
    </div>
    <div class= "form-group">
        <div class= "control-lable col-sm-2">
          <%= f.label :description %>
        </div>
        <div class= "col-sm-8">
          <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Body of article" %>
        </div>
      </div>
        <div class= "form-group">
          <div class= "col-sm-offset-2 col-sm-10">
            <%= f.submit class: 'btn btn-primary btn-lg'%>
          </div>
        </div>
  <% end %>
  <div class= "col-xs-4 col-xs-offset-4">
    [ <%= link_to "Cancel request and return to articles.", articles_path %> ]
  </div>
    </div>
  </div>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<%= will_paginate %>
	<h1 align= "center">Listing Articles</h1>

	<%= render "article", obj: @articles %>
<%= will_paginate %>

app/views/articles/new.html.erb
<center><h1>New Article</h1></center>

<%= render 'form' %>

app/views/articles/search.html.erb
<p id="notice"><%= notice %></p>
<% @articles.each do |article| %>
  <div class="row">
    <div class=" col-xs-8 col-xs-offset-2">
      <div class="well well-lg">
        <div class="article-title">
          
          <%= link_to article.title, article_path(article) %>
        </div>
        <div class="article-body">
          <%= truncate(article.description, length: 100) %>
          <div class= "article-details">

            <small>created by: <%= article.user.first_name if article.user%>

              <%= time_ago_in_words(article.created_at)%> ago,
                last update: <%= time_ago_in_words(article.updated_at)%> ago
            </small>
          </div>
        </div>
       
      </div>
    </div>
  </div>
 <% end %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>
<h4 class="center title">Title: <%= @article.title %></h4>
	
<div class="well col-xs-8 col-xs-offset-2">
	
	<h4 class="center description">
		<strong>
			Description:
		</strong>
	</h4>
	<br>
	<%= @article.description %>




<div class="article-art">
	<%= link_to 'Edit this article', edit_article_path(@article), class: "label label-primary" %> |
	<%= link_to 'Delete this Article', @article, method: :delete, data: { confirm: 'Are you sure?' }, class: "label label-danger" %> |
	<%= link_to 'Back to articles list', articles_path, class: "label label-success"%>
	
</div>

<a> share: <%= social_share_button_tag(@article.title, :url => "http://sample-app.dev/articles/1") %></a>
</div>

app/views/conversations/_conversation.html.erb
<div class="media">
  <div class="media-left">
    <a href="#">
      <ul class="message"><%= image_tag(current_user.image.url(:medium))%></ul>
    </a>
  </div>
  <div class="media-body">
    <h4 class="media-heading">
      <%= conversation.originator.first_name %> <br>
      <small><b>Subject: </b><%= conversation.subject %></small><br>
      <small><b>Sent at: </b><%= time_ago_in_words(conversation.messages.last.created_at)%> ago</small>
    </h4>
    <%= truncate conversation.messages.last.body, length: 145 %>
    <%= link_to "View", conversation_path(conversation)  %>
  </div>
</div>

app/views/conversations/_form.html.erb
<%= form_for :conversation, url: :conversations, html: { class: "" } do |f| %>
    <div class="form-group">
      <%= f.label :send_to %>
      <%= f.select(:recipients, User.all.collect {|p| [ p.first_name, p.id ] }, {}, { multiple: true , class: "form-control" })%>
    </div>
    <div class="form-group">
      <%= f.label :subject %>
      <%= f.text_field :subject, placeholder: "Subject", class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :message %>
      <%= f.text_area :body, class: 'form-control',placeholder: "Type your message here", rows: 4  %>
    </div>
    <%= f.submit "Send Message", class: "btn btn-success" %>
    <% end %>

app/views/conversations/_messages.html.erb
<% @receipts.each do |receipt| %>
    <% message = receipt.message %>
    <div class="media">
      <div class="media-left">
        <ul class='message' ><%= image_tag(current_user.image.url(:medium))%></ul>
      </div>
      <div class="media-body">
        <h4 class="media-heading">
          <%= message.sender.first_name %> <br>
          <small><b>Subject: </b><%= message.subject %></small><br>
          <small><b>Date: </b><%=  message.created_at.strftime("%A, %b %d, %Y at %I:%M%p") %></small>
        </h4>
        <%= message.body %>
      </div>
    </div>
<% end %>

app/views/conversations/new.html.erb
<%= render partial: 'mailbox/folder_view', locals: { is_conversation: true } %>

app/views/conversations/show.html.erb
<div class="row">
  <div class="spacer"></div>
  <div class="col-md-12">
    <%= link_to "Compose", new_conversation_path, class: "btn btn-success" %>
    <div class="spacer"></div>
  </div>

  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-body">
        <%= render 'mailbox/folders' %>
      </div>
    </div>
  </div>

  <div class="col-md-8">
    <div class="panel panel-default">
      <div class="panel-body">
        <%= render partial: 'messages' %>
      </div>
        <div class="panel-footer">
          <%= form_for :message, url: reply_conversation_path(@conversation) do |f| %> 
            <div class="form-group">
              <%= f.text_area :body, placeholder: "Reply Message", rows: 4, class: "form-control" %>
            </div>
            <%= f.submit "Reply", class: 'btn btn-danger pull-right' %>
          <% end %>
        <div class="clearfix"></div>
      </div>
    </div>
  </div>

</div>

app/views/layouts/_footer.html.erb
<div class="container">
	<footer class="footer">
		<small>
			Copyrights &copy;2017, All Rights Reseved  by <a href="https://www.facebook.com/adel.almaleh2">Adel Almaleh</a>
		</small>
		<nav>
			<ul>
				<li><%= link_to "Home", root_path %></li>
				<li><%= link_to "About", welcome_about_path %></li>
				<li><%= link_to "Articles", articles_path %></li>
				<li><%= link_to "New article", new_article_path %></li>
				<li><%= link_to "Terms", '#' %></li>
				<li><%= link_to "Privacy", '#' %></li>
				<li><%= link_to "Support", '#' %></li>
			</ul>
		</nav>
	</footer>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a> <%= link_to "SampleApp", root_path, class: "navbar-brand", id: 'logo'%></a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Article <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a> <%= link_to "All Articles", articles_path %></a></li>
            <li><a> <%= link_to "Create Articles", new_article_path %></a></li>
          </ul>
        </li>
        <% if user_signed_in? %>
        <li><%= link_to "Users", user_index_path %></li>
        <% end %>
      </ul>
      <%= form_tag search_articles_path, method: :get, class: "navbar-form navbar-left", role: "Search" do %>
        <p>
          <%= text_field_tag :search, params[:search], class: "form-control" %>
          <%= submit_tag "search", name: nil, class: "btn btn-default" %>
        </p>
        <% end %>
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li class="profile">
            <%= link_to(image_tag(current_user.image.url(:medium)), user_path(current_user)) %><
          </li>
        <% end %>
        <% if user_signed_in? %>
          <li><%= link_to "Inbox", mailbox_inbox_path %></li>
          <li class="inbox"><%=unread_messages_count%></li> 
          <li><%= link_to current_user.first_name, user_path(current_user)%></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Logout", destroy_user_session_path,:method => :delete %></li>
              <li><%= link_to "Update your account", edit_user_registration_path %></li>
      </ul>
          </li>
        <% else %>
          <li><%= link_to "Sign up", new_user_registration_path %></li>
          <li><%= link_to "Sign in", new_user_session_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SampleApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <%= render 'layouts/navbar'%>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class= "container">


<%= yield %>
    <%= render 'layouts/footer' %>

</body>
</html>

app/views/mailbox/_folder_view.html.erb
<div class="row">
  <div class="spacer"></div>
  <div class="col-md-12">
    
    <p>
      <%= link_to "New", new_conversation_path, class: "btn btn-success" %>
    </p>
    <div class="spacer"></div>
  </div>

  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-body">
        <%= render 'mailbox/folders' %>
      </div>
    </div>
  </div>

  <div class="col-md-8">
    <div class="panel panel-default">
      <div class="panel-body">
        <% if is_conversation %>
            <%= render 'conversations/form' %>
        <% else %>
            <%= render partial: 'conversations/conversation', collection: messages %>
        <% end %> 
      </div>
    </div>
  </div>

</div>

app/views/mailbox/_folders.html.erb
<ul class="nav nav-pills nav-stacked">
  <li class="<%= active_page(:inbox) %>">
    <%= link_to mailbox_inbox_path do  %>
        <span class="label label-danger pull-right"><%=unread_messages_count%></span>
        <em class="fa fa-inbox fa-lg"></em>
        <span>Inbox</span>
    <% end %>
  </li>
  <li class="<%= active_page(:sent) %>">
    <%= link_to mailbox_sent_path do %>

        <em class="fa fa-paper-plane-o fa-lg"></em>
        <span>Sent</span>
    <% end %>
  </li>

app/views/mailbox/inbox.html.erb
<%= render partial: 'mailbox/folder_view', locals: { is_conversation: false, messages: @inbox } %>

app/views/mailbox/sent.html.erb
<%= render partial: 'mailbox/folder_view', locals: { is_conversation: false, messages: @sent } %>w

app/views/shared/_error.html.erb
<% if obj.errors.any? %>
	<div class=	"row">
		<div class= “col-xs-8 col-xs-offset-2”>
			<div class= "panel panel-danger">
				<div class= "panel-heading">
					<h2 class= "panel-title">
						<%= pluralize(obj.errors.count, "error")%>
						prohibited this article from being saved:
					</h2>
					<div class= "panel-body">
						<ul>
							<% obj.errors.full_messages.each do |msg| %>
								<li><%= msg %></li>
							<% end %>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
<% end %>

app/views/users/_following.html.erb
<br>
<div class="container">
    <div class="page-header">
        <% if current_user.first_name  %>
        <% else %>
            <% if current_user.following?(@user) %>
                <%= link_to("Unfollow", unfollow_user_path(@user), :class => 'btn btn-danger' ) %>
            <% else %>
                <%= link_to("Follow" , follow_user_path(@user.to_param), :remote => true, :class =>' btn btn-success' )%>
            <% end %>
        <%end %></h1>
    </div>

<% if @users.any? %>
    <% @users.each do |user| %>
        <%= @user.first_name %>
        <hr>
    <% end %>
<% end %>

app/views/users/_status.html.erb
<% @user ||= current_user %>
<div class="stats">
	<a href="<%= follow_user_path(@user) %>">
		<strong id="following" class="stat">
			<%= @user.follow_count %>
		</strong>
		following
	</a>
	<%= link_to "Follow", follow_user_path(@user)%>
  <%= link_to "Unfollow", unfollow_user_path(@user) %>

app/views/users/index.html.erb
<h1 align= "center"> All Users</h1>
<%= will_paginate %>
<div align= "center">
	<% @users.each do |user| %>
		<ul class= "listing">
			<div class= "row">
				<div class= "well col-md-4 col-md-offset-4">
					<ul><%= link_to image_tag(user.image.url(:thumb))%></ul>
					<ul> <%= link_to user.first_name, user %></ul>
					<ul><small><%= pluralize(user.articles.count, "article") if user.articles %></small>
					</ul>
				</div>
			</div>
		</ul>
	<% end %>
</div>
<%= will_paginate %>

app/views/users/show.html.erb
<div >		
	<h1 class= "text" align= "center">Welcome to <%= @user.first_name %>'s page</h1>
	<ul ><%= image_tag(@user.image.url(:medium))%></ul>
		<%= render "status" %>
	<h2 class= "text" align= "center">List of <%= @user.first_name %>'s Articles</h2>
		
		<%= render "articles/article", obj: @user.articles %>
</div>

app/views/welcome/_index.html.erb
<h1 class= "text" align= "center">Hello <%= current_user.first_name %></h1>
<h2 class= "profile" align= "center"> <%= link_to(image_tag(current_user.image.url(:medium)), user_path(current_user)) %></h2>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/home.html.erb
<% if !user_signed_in? %>
	<div class="jumbotron">
	  <h1>welcome to SampleApp</h1>
	  
	  <p><%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary btn-lg" %></p>
	  <p><%= link_to "Sign in", new_user_session_path, class: "btn btn-primary btn-lg " %></p>
	</div>
<% else %>
	<%= render 'index' %>
<% end %>